### PR TITLE
add StakingCabin gentx and peer

### PR DESCRIPTION
**Pull request by richard-stakingcabin**
## Checklist

- [ ] New and updated code has appropriate documentation
- [ ] New and updated code has new and/or updated testing
- [ ] Required CI checks are passing
- [ ] Visual proof for any user facing features like CLI or documentation updates
- [ ] Linked issues closed with keywords

### CODE REVIEW

**Review by liamsi — COMMENTED** [review]
Can you rebase on the latest master please? Or close this and resubmit in a new PR? We made changes to our CI and there have been some fixes.

**Review by liamsi — CHANGES_REQUESTED** [review]
If I look at the CI output this still looks like it is running an old version:
image

Can you ensure that you use the latest master branch please.

**Comment by liamsi** [comment]
Can you resolve the merge conflicts. I can't do it for you b/c you disabled that maintainers can edit PRs from your fork (which is fine btw).

**Comment by richard-stakingcabin** [comment]
Sorry for any inconvenience I caused. Seems can't enable maintainers  edit PRs for repo fork under organization. I fork under my personal account and submit pr again

**Pull request closed without merging**
