### PR TITLE
Updating Spidey Peer after migrating Validator node due to hardware issues.

### PR DESCRIPTION
**Pull request by spidey-169**
## Checklist

- [ ] New and updated code has appropriate documentation
- [ ] New and updated code has new and/or updated testing
- [ ] Required CI checks are passing
- [ ] Visual proof for any user facing features like CLI or documentation updates
- [ ] Linked issues closed with keywords

### CODE REVIEW

**Comment by spidey-169** [comment]
@YazzyYaz Could you look into this when you get chance. Let me know if there are any issues here. Thanks

**Review by jcstein — APPROVED** [review]

**Comment by spidey-169** [comment]
@jcstein Lets get this merged soon if possible! Do let me know If I am missing anything. Thanks

**Comment by jcstein** [comment]
gm @spidey-169 - pinging some others for review and merge

**Comment by jcstein** [comment]
cc @YazzyYaz @liamsi

**Review by YazzyYaz — APPROVED** [review]

**Review by liamsi — APPROVED** [review]

**Pull request merged**
