### PR TITLE
Add Blockpower Capital 

### PR DESCRIPTION
**Pull request by BlockpowerCapital**

### CODE REVIEW

**Comment by mindstyle85** [comment]
hey @BlockpowerCapital your stake amount should be 5m tia, please fix it

**Comment by BlockpowerCapital** [comment]
@mindstyle85 Updated

**Comment by mindstyle85** [comment]
ah, @BlockpowerCapital really sorry, could you change the max rate to something less than 1? there wont be any delegation competition here or restake stuff

**Comment by BlockpowerCapital** [comment]
@mindstyle85 okay, I don't see the restrictions, it's just a habit of test networks.

**Comment by mindstyle85** [comment]
hello @BlockpowerCapital  your gentx failed on our tests, with the most generic error  (signature verification failed; please verify account number (0) and chain-id (blockspacerace-0): unauthorized), so i would kindly ask you to redo your gentx and make sure you init the node with blockspacerace-0 chain-id as well as make sure you do it with celestia-app v0.12.0, thanks!

**Comment by mindstyle85** [comment]
hey @BlockpowerCapital still waiting on your gentx resubmission

**Pull request merged**
