### PR TITLE
Validatus gentx and peers.

### PR DESCRIPTION
**Pull request by Validatus**
Let's power the Celestia network together - A huge thank you to the Celestia Team!

### CODE REVIEW

**Review by liamsi — APPROVED** [review]
🎉

**Review by liamsi — CHANGES_REQUESTED** [review]
> signature verification failed; please verify account number (0) and chain-id (celestia): unauthorized

**Comment by Validatus** [comment]
We have updated our gentx with the proper flag --ip="0.0.0.0" - cryptography is so strong.
**Sorry for that!
Many thanks!**

**Review by liamsi — APPROVED** [review]
🎉

**Review by adlerjohn — APPROVED** [review]

**Pull request merged**
