### PR TITLE
Gentx ContributionDAO and peer

### PR DESCRIPTION
**Pull request by llPorZall**
## Checklist

- [ ] New and updated code has appropriate documentation
- [ ] New and updated code has new and/or updated testing
- [ ] Required CI checks are passing
- [ ] Visual proof for any user facing features like CLI or documentation updates
- [ ] Linked issues closed with keywords

### CODE REVIEW

**Review by YazzyYaz — APPROVED** [review]

**Review by YazzyYaz — CHANGES_REQUESTED** [review]
You must delegate 80% of your Blockspace Race rewards from that account for this gentx file

**Comment by llPorZall** [comment]
@YazzyYaz Fixed sorry for my misunderstand

**Review by liamsi — APPROVED** [review]

**Comment by Bidon15** [comment]
@llPorZall please rebase this PR to latest changes 🙏

**Comment by liamsi** [comment]
not necessary: will update

**Review by adlerjohn — APPROVED** [review]

**Pull request merged**
