### PR TITLE
add gentx Staker Space

### PR DESCRIPTION
**Pull request by ilhanu**
For now just the gentx, the peer file will be updated later next week.

### CODE REVIEW

**Review by liamsi — COMMENTED** [review]
Can you please rebase on the latest master or close reopen the same changes in a new PR? That would trigger CI to correctly fetch the most recent changes/fixes.

**Comment by liamsi** [comment]
can you rebase one more time? the valid-gentx is green but it is not ran correctly due to: https://github.com/celestiaorg/networks/issues/398

**Review by liamsi — CHANGES_REQUESTED** [review]
https://github.com/celestiaorg/networks/pull/364#issuecomment-1775146505

**Review by liamsi — APPROVED** [review]
🎉

**Comment by liamsi** [comment]
Can you resolve the merge conflicts.

**Review by ilhanu — COMMENTED** [review]
Had to merge the latest changes in the fork before fixing the conflict.

**Review by liamsi — APPROVED** [review]
🎉

**Review by YazzyYaz — APPROVED** [review]

**Pull request merged**
