### PR TITLE
Adding gentx transaction for blockdaemon for genesis creation.

### PR DESCRIPTION
**Pull request by jer117**
Adding gentx transaction for blockdaemon for genesis creation.

### CODE REVIEW

**Review by liamsi — CHANGES_REQUESTED** [review]
> signature verification failed; please verify account number (0) and chain-id (celestia): unauthorized

**Comment by jer117** [comment]
Hi @liamsi, I believe I have fixed the issue. Please let me know if anymore arise.

**Comment by YazzyYaz** [comment]
@jer117 this isn't the Github handle you guys submitted for making the PR. hence why the test is failing.

**Comment by jer117** [comment]
@YazzyYaz This should be the one, I used this for the last gentx for testnet too.

**Comment by jer117** [comment]
@YazzyYaz You are right, I see the ones we sent in.

discord
dsh5436	
macunha.
JackBlockdaemon
github
dshyionak-bd
macunha1
JackPMallon

**Comment by jer117** [comment]
@YazzyYaz Got it re submitted for here.

https://github.com/celestiaorg/networks/pull/495

**Pull request closed without merging**
