### PR TITLE
fix bash

### LINKED ISSUE #398: ci: run-network job does not get executed
Validate Genesis / run-network (pull_request) does not seem to run:
`/home/runner/work/_temp/1310e5a5-7d32-4bf2-bf04-e2e09c49dac5.sh: line 1: [[-f: command not found`

image

https://github.com/celestiaorg/networks/actions/runs/6606039623/job/17941835312?pr=397

### PR DESCRIPTION
**Pull request by MSevey**
## Overview

Expected Pass with no gentx: https://github.com/celestiaorg/networks/actions/runs/6606628562/job/17943015465
Expected Failure with bad gentx: https://github.com/celestiaorg/networks/actions/runs/6606653515/job/17943071797?pr=399

Closes #398

### CODE REVIEW

**Comment by MSevey** [comment]
@evan-forbes ideas on this network timeout?

https://github.com/celestiaorg/networks/actions/runs/6606882228/job/17943550238?pr=399
```
Error: timeout (10s) exceeded waiting for network to reach height
```

**Comment by evan-forbes** [comment]
did the gentx change at all or was this a flake? 

If the timeout is only 10s we might want to increase that as spinning up a single network takes 4-7s, and perhaps the larger genesis is also taking extra time

**Comment by liamsi** [comment]
I'd recommend closer to a minute or so. Even locally, on my machine I used waiting of 200 microseconds per account. And this file has roughly 200k accounts.

**Review by liamsi — APPROVED** [review]
We can fix [this](https://github.com/celestiaorg/networks/pull/399#issuecomment-1774233432) in Evan's branch.

**Review by Bidon15 — APPROVED** [review]

**Review by YazzyYaz — APPROVED** [review]

**Comment by liamsi** [comment]
@MSevey @evan-forbes 
https://github.com/celestiaorg/celestia-app/commit/4dc70d3617229abbe24efbde183668887072995a

**Pull request merged**
