### PR TITLE
Create 0xKnowledgE.json

### PR DESCRIPTION
**Pull request by homodeus042**
## Checklist

- [ ] New and updated code has appropriate documentation
- [ ] New and updated code has new and/or updated testing
- [ ] Required CI checks are passing
- [ ] Visual proof for any user facing features like CLI or documentation updates
- [ ] Linked issues closed with keywords

### CODE REVIEW

**Review by YazzyYaz — APPROVED** [review]

**Comment by mindstyle85** [comment]
hey @homodeus042 you have wrong denom in your gentx, its `utiaT` instead of `utia`, please redo the gentx and resubmit, thanks!

**Comment by homodeus042** [comment]
ok I understand. I'm fixing now

mindstyle85 ***@***.***>, 10 Mar 2023 Cum, 03:28 tarihinde
şunu yazdı:

**Comment by homodeus042** [comment]
https://github.com/celestiaorg/networks/compare/master...homodeus042:networks-1:master#diff-41f2299b2b96b60ff1d9cf31e245b4fbd0d5bd6c67ed008259dbb74fa5bea2cb
I edited.


Murad Rzayev ***@***.***>, 10 Mar 2023 Cum, 09:29 tarihinde
şunu yazdı:

**Comment by mindstyle85** [comment]
hey @homodeus042 please dont use max rate 1, make that normal, and also after that please make the PR for the changes to the repo

**Comment by homodeus042** [comment]
https://github.com/celestiaorg/networks/pull/289

I edited

mindstyle85 ***@***.***>, 10 Mar 2023 Cum, 13:12 tarihinde
şunu yazdı:

**Pull request merged**
