### PR TITLE
Create binary_holdings.json

### PR DESCRIPTION
**Pull request by wpank**
Add Binary Holdings

### CODE REVIEW

**Comment by rooiie** [comment]
Hey @wpank  your stake amount should be 5m tia, could you please fix it

**Comment by rooiie** [comment]
Also could you lower your rates to normal values please?

**Comment by wpank** [comment]
@rooiie updated

**Comment by mindstyle85** [comment]
ill leave it with max rate 1 but dont raise to anywhere near that level as its not something we "like" to see, even if its a testnet

**Comment by wpank** [comment]
> ill leave it with max rate 1 but dont raise to anywhere near that level as its not something we "like" to see, even if its a testnet

Err so is the current gentx fine or should I change anything? (I see most other prs have been merged or accepted except this one)

**Review by YazzyYaz — APPROVED** [review]

**Pull request merged**
