### PR TITLE
add DokiaCapital

### PR DESCRIPTION
**Pull request by mabalaru**
## Checklist

- [ ] New and updated code has appropriate documentation
- [ ] New and updated code has new and/or updated testing
- [ ] Required CI checks are passing
- [ ] Visual proof for any user facing features like CLI or documentation updates
- [ ] Linked issues closed with keywords

### CODE REVIEW

**Comment by rooiie** [comment]
@mabalaru please change your rates to something normal. it needs to be way below 1. thanks in advance

**Comment by mabalaru** [comment]
@rooiie 
Commission = 0.05
max-commission = 1

New PR: https://github.com/celestiaorg/networks/pull/286

**Comment by rooiie** [comment]
@mabalaru saw you opened an other, please close this one.

**Comment by rooiie** [comment]
@mabalaru thanks, the other one is good

**Pull request closed without merging**
